export type ContestType = {
    year: number,
    jrk: number,
    city: string,
    venue: string,
    country_name: string,
    country_iso: string,
    country_flag: string,
    participants: number,
    previous: number,
    next: number,
    voting: string,
    semi1_date: string,
    semi2_date: string,
    final_date: string,
    hosts: string,
    wiki_link: string,
    image: string,
    thumb: string,
    image_title: string,
    image_source: string,
    image_source_link: string,
    image_2: string,
    thumb_2: string,
    image_title_2: string,
    image_source_2: string,
    image_source_link_2: string,
    final: ParticipantType[],
    semi1: ParticipantType[],
    semi2: ParticipantType[]
}

export type ParticipantType = {
    jrk: number,
    country_name: string,
    country_iso: string,
    country_flag: string,
    performer: string,
    song: string,
    place: number,
    points: number,
    image: string,
    thumb: string,
    image_title: string,
    image_source: string,
    image_source_link: string,
    video_embed: string,
    video_title: string
}